server.address=127.0.0.1
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=riovas
spring.datasource.hikari.data-source-properties.preferQueryMode=extended